### ISSUE TITLE
Example compose file / usage of prefix parameter

### ISSUE THREAD

**Issue by marcusfey** [tenox7/wfm#50]
I would like to use wfm behind an nginx, both in docker, ideally with docker compose (separate files).

My docker-compose.yml for wfm currently is:
```yaml
version: '3'
services:
  wfm:
    image: tenox7/wfm:latest
    user: 1001:1001
    container_name: wfm
    #command: -prefix=/data:/wfm
    volumes:
      - ./wfmpasswd.json:/etc/wfmusers.json
      - /:/data:ro
    expose:
      - 8080
    restart: always
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true
 ```
nginx.conf:
```
{ ...
    location /wfm/ {
        proxy_pass         http://wfm:8080/;
    }
...
}
```

I can access wfm on `<host>/wfm/`but all the directory links lead to `<host>/<dir>`instead of `<host>/wfm/<dir>`

My understanding was that adding `-prefix` fixes this. But if I add the commented line above (`command: -prefix=/data:/wfm`):
 - wfm is only available under `<host>/wfm/wfm/`
 - the links inside wfm lead to `<host>/wfm/<dir>` thus "outside" of `/wfm/wfm`
 
How can I fix this?

Thanks!

PS: The documentation of [`prefix`](https://github.com/tenox7/wfm#prefix) is a bit misleading. The text contains "data" and "wfm" but the solution is "httppath". It might be helpful to pick up one of the examples, not something entirely else.
